name: Build

on:
  push:
    branches: [ 'develop', 'feature/**', '*fix/**', 'release/**' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        config: [Debug, Release]

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v3

    - name: Generate build system
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE:STRING=${{matrix.config}}

    - name: Build targets
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.config}}

    - name: Perform tests
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{matrix.config}} -V

    - name: Create package
      working-directory: ${{github.workspace}}/build
      run: cpack -C ${{matrix.config}} -G ZIP -V
